import React, { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom'; // <-- add this
import App from './App';
import './index.css';
function setForLocalDev() {
  const dev_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiI1MDg4NiIsImVtYWlsIjoiY2hhbmRyYXNtcmZ0QGdtYWlsLmNvbSIsIm5hbWUiOiJDaGFuZHJhIiwiYWxsb3dlZC1hY3Rpb25zIjpbIkhNUy1QLUNDR0FILVIiLCJITVMtUC1SQ0FULVIiLCJTVC1QLU5URi1SIiwiSE1TLVAtQ0NHU1JEX1JXIiwiSE1TLVAtQ0NDLVJXIiwiU1QtUC1ERVMtUiIsIkhNUy1QLUNFQi1SVyIsIkhNUy1QLUFETS1SVyIsIk1EQy1QLVNPUi1SIiwiTURDLUFQSS1DRFItUiIsIlNULVItQ0RSIiwiRkUtUC1GUy1SVyIsIkhNUy1QLUNDTUJQQi1SVyIsIk1EQy1QLVRSQi1SVyIsIkhNUy1QLVBTT1BCLVJXIiwiSE1TLVAtUENDU0RfUlciLCJNREMtUC1SREUtUlciLCJITVMtUC1TVU1FLVJXIiwiSE1TLVAtUEFTLVJXIiwiSE1TLVAtSUItUiIsIkhNUy1QLUdMQlUtUiIsIk1EQy1QLVBURS1SVyIsIkhNUy1QLUNDR01QQi1SVyIsIkhNUy1QLU9QSCIsIk1EQy1BUEktVEhSLVIiLCJNREMtUC1SRUctUlciLCJNREMtUC1QTlAtUiIsIkhNUy1QLVBDQi1SVyIsIkhNUy1QLVBHRUItUlciLCJITVMtUC1IU04tUlciLCJITVMtUC1TUkJELVJXIiwiTURDLUFQSS1SREwtUlciLCJITVMtUC1QT1BVQVMtUlciLCJNREMtUC1BRC1SVyIsIkZFLVAtRkFMLVJXIiwiSE1TLVAtV1JRLVJXIiwiSE1TLVAtUFNCLVJXIiwiSE1TLVAtUFBELVJXIiwiSE1TLVAtSE1TIiwiTURDLVAtUE5QLVJXIiwiSE1TLVAtQkxLLVIiLCJITVMtUC1QR1MtUlciLCJTVC1SLUEiLCJITVMtUC1HV0wtUiIsIkhNUy1QLU5TLVJXIiwiU1QtQVBJLUNSRC1SVyIsIkhNUy1QLUNDU1BTRC1SVyIsIkdQLVAtR0NOLVIiLCJITVMtUC1TSURFQkFSIiwiSE1TLVAtU1RBLVJXIiwiSE1TLVAtUE9QUERCLVJXIiwiSE1TLVAtT1BTUkJELVJXIiwiSE1TLVAtUEdQQlQtUiIsIk1EQy1QLUdEVFMtUlciLCJITVMtUC1QSVBBLVJXIiwiSE1TLVAtU1VNLVJXIiwiSE1TLVAtUFNSQkQtUlciLCJITVMtUC1QU0ctUlciLCJITVMtUC1QQ09QUC1SVyIsIkhNUy1QLVNULVJXIiwiSE1TLVAtQ1MtUlciLCJGRS1QLUZVQi1SVyIsIkhNUy1QLUdPUEJOLVIiLCJTVC1QLVRETC1SIiwiSE1TLVAtUE1DLVJXIiwiU1QtQVBJLUFNQy1SVyIsIkhNUy1QLUNDT1BQQi1SVyIsIkhNUy1QLVBHRUItUiIsIkhNUy1QLUlQSCIsIkhNUy1QLURSTS1SIiwiU1QtUC1ERVMtUlciLCJNREMtQVBJLVJUUy1SIiwiSE1TLVAtQ0NTVFNELVJXIiwiSE1TLVAtUE9QU1JCRC1SVyIsIkhNUy1QLVNVTUQtUlciLCJITVMtUC1HTEJULVIiLCJGRS1QLUZSLVJXIiwiTURDLVAtUkVHLVIiLCJTVC1BUEktQlJELVJXIiwiSE1TLVAtQ0NHUkItUlciLCJITVMtUC1QR1NSRC1SVyIsIk1EQy1BUEktQVQtUiIsIk1EQy1BUEktQVQtUlciLCJNREMtUC1PU0ItUlciLCJITVMtUC1TT1BFLVJXIiwiSE1TLVAtU09QQi1SVyIsIkhNUy1QLUNDR0FTLVJXIiwiSE1TLVAtQ0NVUEItUlciLCJITVMtUC1HQUUtUiIsIkhNUy1QLUNDR0FILVJXIiwiU1QtQVBJLUVNUC1SIiwiSE1TLVAtQ0NDUkItUlciLCJITVMtQVBJLURMRC1SVyIsIk1EQy1QLUdBRC1SVyIsIkhNUy1QLU9QUEItUiIsIlNULVAtQ01ULVIiLCJTVC1QLVRETC1SVyIsIkhNUy1QLVBTSVAtUlciLCJITVMtUC1TVU0tUiIsIlNULVAtQlJELVIiLCJITVMtUC1PUy1SVyIsIk1EQy1QLUNERS1SVyIsIkZFLVAtRkctUlciLCJITVMtUC1DQ1BSUC1SVyIsIkhNUy1QLUFETUwtUlciLCJNREMtQVBJLUxCTi1SIiwiSE1TLVAtREJVRFItUiIsIk1EQy1QLVVBUy1SVyIsIkhNUy1QLVBHTEJVLVJXIiwiSE1TLVAtUEdBUy1SIiwiSE1TLVAtUEREUy1SVyIsIkhNUy1QLUNERFMtUlciLCJGRS1SLUZBIiwiTURDLVAtQVNNLVJXIiwiRkUtUC1GU0ItUlciLCJITVMtUC1TUkdQRC1SVyIsIlNULVAtQ01ULVJXIiwiSE1TLVAtU1VNQS1SVyIsIkhNUy1QLUNUSUEtUlciLCJNREMtUi1SRUMiLCJITVMtUC1EQiIsIkhNUy1QLUFBLVJXIiwiRkUtUC1GRi1SVyIsIkhNUy1QLUdQQlQtUiIsIkhNUy1QLVBPUFNSLVJXIiwiSE1TLVItUEgiLCJITVMtUC1DVEktUlciLCJITVMtUC1DQ08tUlciLCJNREMtUC1HQVQtUlciLCJNREMtQVBJLVBBVCIsIkhNUy1QLURMRC1SVyIsIlNULVAtU05PLVJXIiwiSE1TLVAtUERCLVJXIiwiSE1TLVAtR09QUy1SIiwiSE1TLVAtUEhWU0ItUlciLCJITVMtUC1QUEQtUiIsIkhNUy1QLVBDQl9SVyIsIkZFLVAtRlVTLVJXIiwiSE1TLVAtQ09QUC1SVyIsIk1EQy1QLVBOUFItUiIsIkhNUy1QLVBTTS1SVyIsIk1EQy1BUEktUEFULVIiLCJGRS1QLUZHTC1SIiwiRkUtUi1GQS1SVyIsIk1EQy1BUEktR0FTLVIiLCJITVMtUC1OU0QtUlciLCJITVMtUC1QRkItUlciLCJITVMtUC1DQ0lQQUItUlciLCJNREMtUC1DQS1SVyIsIkZFLVAtRkdGLVIiLCJNREMtUC1FRi1SVyIsIkhNUy1QLUNDR1JQLVJXIiwiU1QtUC1OVEYtUlciLCJITVMtUC1DQ0dQQi1SVyIsIkhNUy1QLVZMLVJXIiwiSE1TLVAtUEdMQlUtUiIsIkhNUy1QLVBHUEJULVJXIl0sImFsbG93ZWQtZGF0YSI6WyJTSEIwMDEiXSwiaG9zcGl0YWxfY29kZSI6IlNIMDAxIiwiaG1zX3BhZ2VzIjpbMTI4LDEyOSwzLDEwMSw1LDEwMiwxMCw0Myw0NCwxMTMsMTgsMTksMTE0LDU1LDEyNyw0NSw1MF0sImFsbG93ZWQtb3V0bGV0cyI6WyJPTEVUMDAzIiwiT0xFVDAwMSIsIk9MRVQwMDIiLCJPTEVUMDA0Il0sImlzcyI6Imh0dHBzOi8vbGFiLnNoaW5vdmEuaW4vIiwiaWF0IjoxNzgzNDgyODQ5LCJleHAiOjE3ODM1Njk4NDl9.Q_hIv-42vw_qn2E_gU-ijSOWjXsGhJaAObSwpob9zJxDsAC60UNltkrNOjufOpFqNGe_W-TxWOzlG4N343z19oJRPBn0vE1T2QM8SVoDRRFgwxPmNddECY_TzA6gRv4n5Q9yFFkGomd_W1py7WLEUjYNOgAir5SzNJEFmjvdlBeqzQU5Ok7ES6HRMTt-R8LxVhHdhHfqNMlI1Zk3jkVh8BlaSZHXcFZhur8Im2BoEufwiaNTj6iOC8lmor9VueWiVA1zDgkBF3AaDjZoSKQEYwFzF8eLVHyUynmSY6bJLtNWG9nTySMb5sYJVW1v6nT6diQfzks-BZB_whXW74THKQ";
 

  localStorage.setItem("access_token", dev_token);
  console.log("🔧 Development token is empty - will redirect to login");
  const selectedBranch = "SHB001";
  localStorage.setItem("selected_branch", selectedBranch);
  const selectedOutlet = "OLET002";
  localStorage.setItem("selected_outlet", selectedOutlet);

  return dev_token;
}
function validate(token) {
  try {
    const payload = JSON.parse(atob(token.split('.')[1]));
    const now = Math.floor(Date.now() / 1000);
    if (!payload.exp || payload.exp < now) {
      throw new Error("Token expired");
    }
    return payload;
  } catch (err) {
    throw new Error("Invalid token");
  }
}
const BASE_PATH = process.env.PUBLIC_URL;
function RootRenderer() {
  const [isValidToken, setIsValidToken] = useState(false);
  useEffect(() => {
    let accessToken = localStorage.getItem("access_token");
    if (!accessToken && process.env.REACT_APP_LOCAL_DEV_ENVIRONMENT === 'true') {
      accessToken = setForLocalDev();
    }
    try {
      if (!accessToken) throw new Error("No token found");
      const payload = validate(accessToken);
      localStorage.setItem("user_payload", JSON.stringify(payload));
      setIsValidToken(true);
    } catch (err) {
      console.error("Token validation failed:", err.message);
      localStorage.removeItem("access_token");
      localStorage.removeItem("user_payload");
      // window.location.href = process.env.REACT_APP_LOGIN_REDIRECT_URL;
    }
  }, []);
  return isValidToken ? (
<BrowserRouter  basename={BASE_PATH}>
  <App />
</BrowserRouter>

  ) : null;
}
const container = document.getElementById('root');
const root = createRoot(container);
root.render(
  <StrictMode>
    <RootRenderer />
  </StrictMode>
);